# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install matplotlib

    - name: Run
      run: go run bbst_prof.go > /tmp/bench.csv

    - uses: actions/upload-artifact@v3
      with:
        name: bench.csv
        path: /tmp/bench.csv
    - name: createFigure
      run: python3 visualize.py /tmp/bench.csv /tmp/complexity.png

    - uses: actions/upload-artifact@v3
      with: 
        name: complexity.png
        path: /tmp/complexity.png
